apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: duel-server
spec:
  serviceName: "duel"
  replicas: 1
  selector:
    matchLabels:
      app: duel-server
  template:
    metadata:
      labels:
        app: duel-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: minecraft
          image: ghcr.io/yyuhdev/duel:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MEMORY
              value: "4096"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-deployment
                  key: mongodb-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-deployment
                  key: mongodb-password
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets-deployment
                  key: mongodb-host
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secrets-deployment
                  key: mongodb-database
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets-deployment
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets-deployment
                  key: redis-port
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - name: data
              mountPath: /mnt/volume
      volumes:
        - name: data
          emptyDir: {}
