apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: limbo-server
spec:
  serviceName: "limbo"
  replicas: 1
  selector:
    matchLabels:
      app: limbo-server
  template:
    metadata:
      labels:
        app: limbo-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: minecraft-limbo
          image: ghcr.io/yyuhdev/limbo:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MEMORY
              value: "4096"
          ports:
            - containerPort: 25565
              name: limbo
          volumeMounts:
            - name: data
              mountPath: /mnt/volume
      volumes:
        - name: data
          emptyDir: {}
