apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby-server
spec:
  serviceName: "lobby"
  replicas: 1
  selector:
    matchLabels:
      app: lobby-server
  template:
    metadata:
      labels:
        app: lobby-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: minecraft-lobby
          image: ghcr.io/yyuhdev/sandbox:lobby
          imagePullPolicy: Always
          env:
            - name: SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MEMORY
              value: "4096"
          ports:
            - containerPort: 25565
              name: lobby
          volumeMounts:
            - name: data
              mountPath: /mnt/volume
      volumes:
        - name: data
          emptyDir: {}
